using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mental_Capacity_Assessments.Models
{
    public class QuestionsInitializer
 : System.Data.Entity.DropCreateDatabaseAlways<Mental_Capacity_AssessmentsContext>
    {
        protected override void Seed(Mental_Capacity_AssessmentsContext context)
        {
            context.Questions.Add(new Questions { Description = "What is the decision to be made and does it need to be made now?", id = "1", yes_button = "1", no_button = "1", yes_next = "3", no_next = "2" });
            context.Questions.Add(new Questions { Description = "Lack of capacity is linked to a specific decision at the specific time. Before you can assess capacity, you must be clear about the decision to be made and whether the decision can wait.", id = "2" });
            context.Questions.Add(new Questions { Description = "Is the person age 16yrs or more?", id = "3", yes_button = "1", no_button = "1", yes_next = "5", no_next = "4" });
            context.Questions.Add(new Questions { Description = "Parts of the MCA apply to those aged 16yrs or more and is not applicable to those under the age of 16yrs. <br/> Advance Decisions can only be made by those over the age of 18. Alternative guidance for those under the age of 16 can be found by looking at the specific laws in relation to capacity and those under 16.", id = "4" });
            context.Questions.Add(new Questions { Description = "Have you started the assessment process with the assumption that the person has capacity to make the specific decision?", id = "5", yes_button = "1", no_button = "1", yes_next = "7", no_next = "6" });
            context.Questions.Add(new Questions { Description = "You must always begin with the assumption that the person has capacity to make a particular decision unless it can be established that they have not.", id = "6" });
            context.Questions.Add(new Questions { Description = "Have you supported the person to make their own decision?", id = "7", yes_button = "1", no_button = "1", yes_next = "9", no_next = "8" });
            context.Questions.Add(new Questions { Description = "A person should not be assessed as unable to make a decision unless all attempts to support and help them have been made. In order to make a valid decision you must provide all of the relevant information in a format that supports them to understand before assessing their capacity to make the decision.", id = "8" });
            context.Questions.Add(new Questions { Description = "Do you consider the decision made by the person to be unwise?", id = "9", yes_button = "1", no_button = "1", yes_next = "10", no_next = "11" });
            context.Questions.Add(new Questions { Description = "An unwise decision should not be mistaken for a lack of capacity. You must recognise the difference between an unwise decision and one based on a lack of understanding of risk or the inability to weigh and judge the relevant information.", id = "10" });
            context.Questions.Add(new Questions { Description = "Does the person have an impairment of the mind or brain(either temporary or permanent) such as dementia, learning disability, confusion, concussion etc?", id = "11", yes_button = "1", no_button = "1", yes_next = "13", no_next = "12" });
            context.Questions.Add(new Questions { Description = "The person does not lack capacity as defined within the Mental Capacity Act and is therefore capable of consenting to a decision or refusing treatment.", id = "12" });
            context.Questions.Add(new Questions { Description = "1. Can the person understand the information relative to the decision? <br/> (Failure of one or more of these points will determine a lack of capacity and a Best Interests Decision will need to be made.)", id = "13", yes_button = "1", no_button = "1", yes_next = "15", no_next = "14" });
            context.Questions.Add(new Questions { Description = "If the person is unable to understand the relevant information (after they have received help to make their own decision) and this is caused by the impairment or disturbance of the mind or brain, they lack capacity to make the decision. <br/> Proceed to Best Interest Decision section", id = "14", yes_button = "6", yes_next = "22" });
            context.Questions.Add(new Questions { Description = "2. Can the person retain the relevant information long enough to be able to make the decision?", id = "15", yes_button = "1", no_button = "1", yes_next = "17", no_next = "16" });
            context.Questions.Add(new Questions { Description = "If the person is unable to retain the information for long enough to make the decision and this is caused by a disturbance of the mind or brain, they lack capacity to make the decision. <br/> Proceed to Best Interest Decision", id = "16", yes_button = "6", yes_next = "22" });
            context.Questions.Add(new Questions { Description = "3. Can the person use or weigh the relevant information to make the decision? ", id = "17", yes_button = "1", no_button = "1", yes_next = "19", no_next = "18" });
            context.Questions.Add(new Questions { Description = "If the person is unable to use or weigh the relevant information and this is caused by a disturbance of the mind or brain, they lack capacity to make the decision. Proceed to Best Interest Decision section", id = "18", yes_button = "6", yes_next = "22" });
            context.Questions.Add(new Questions { Description = "4. Can the person communicate their decision by any means (e.g. speech, sign language)?", id = "19", yes_button = "1", no_button = "1", yes_next = "55", no_next = "20" });
            context.Questions.Add(new Questions { Description = "If the person is unable to communicate their decision in any way and this is caused by a disturbance of the mind or brain, they lack capacity to make the decision. Proceed to Best Interest Decision", id = "20", no_button = "0", yes_button = "9", yes_next = "22" });
            context.Questions.Add(new Questions { Description = "Other considerations:<br/> You must try to determine if the person has a valid advance decision to refuse the treatment you wish to give in their best interest ?<br/> Who else can make a decision in someone''s best interest if they are found to lack capacity ? <br/> \u2022 donee of a Lasting Power of Attorney Health and Welfare or Financial / Court Appointed Deputy <br/> \u2022 Independent Mental Capacity Advocate(IMCA) <br/>\u2022 Clinician or other decision maker ", id = "21" });
            context.Questions.Add(new Questions { Description = "If the person is found to lack capacity for the decision and requires someone to act in their best interests, that person could be:<br/> \u2022 Someone with Lasting Power of Attorney(LPA) or Court Appointed Deputy <br/> \u2022 Independent Mental Capacity Advocate(IMCA) <br/> \u2022 Clinician or other decision maker ", id = "22", yes_button = "3", yes_next = "23" });
            context.Questions.Add(new Questions { Description = "Is this a health or social care decision where a simple response is needed? E.g. there is no requirement to involve the Court of Protection etc.", id = "23", yes_button = "1", no_button = "1", yes_next = "25", no_next = "24" });
            context.Questions.Add(new Questions { Description = "If the intervention required is urgent or an emergency – <b>you must proceed without delay</b>. <br/> In all other circumstances apply the best interests checklist to the decision to be made and the decision maker in consultation with carers, IMCA or other relevant individuals must decide what is in the persons best interest.", id = "24" });
            context.Questions.Add(new Questions { Description = "Have you involved/consulted with others (partner, relatives or carers) who know the persons wishes and can speak on their behalf?", id = "25", yes_button = "1", no_button = "1", yes_next = "27", no_next = "26" });
            context.Questions.Add(new Questions { Description = "If it is practicable and appropriate, you must consult with at least one person to speak on behalf of the person to determine the past and present wishes, feelings, beliefs and values to find out what they would consider to be in their best interests.  <br/> If there is no one to speak on the persons behalf, it may be appropriate to consider requesting an Independent Mental Capacity Advocate(IMCA)", id = "26", yes_button = "8", yes_next = "38" });
            context.Questions.Add(new Questions { Description = "Have you avoided making assumptions based on the persons age, appearance, condition or behaviour?", id = "27", yes_button = "1", no_button = "1", yes_next = "29", no_next = "28" });
            context.Questions.Add(new Questions { Description = "You should never make decisions for the person based on personal judgments as these could be considered to be discriminatory.", id = "28" });
            context.Questions.Add(new Questions { Description = "Can you determine the person previous wishes or find any statements made when they still had capacity that will assist you to make this decision?", id = "29", yes_button = "1", no_button = "1", yes_next = "30", no_next = "31" });
            context.Questions.Add(new Questions { Description = "The previous decisions of the person, now lacking capacity, take precedence over partners, relatives and other parties.<br/> Advance statements(verbal or written) when the person had capacity are not legally binding but the decision maker is legally bound to take into account and cannot ignore it.<br/> Is there an Advance Decision to refuse treatment in existence that conflicts with the decision to be made as this is legally binding even if others disagree.", id = "30" });
            context.Questions.Add(new Questions { Description = "Is capacity likely to improve or return?", id = "31", yes_button = "1", no_button = "1", yes_next = "32", no_next = "33" });
            context.Questions.Add(new Questions { Description = "Postpone the decision until capacity has returned if it is a non urgent decision.", id = "32" });
            context.Questions.Add(new Questions { Description = "Can the decision wait until capacity returns?", id = "33", yes_button = "1", no_button = "1", yes_next = "34", no_next = "35" });
            context.Questions.Add(new Questions { Description = "Postpone the decision until capacity has returned", id = "34" });
            context.Questions.Add(new Questions { Description = "Have you considered the least restrictive option?", id = "35", yes_button = "1", no_button = "1", yes_next = "37", no_next = "36" });
            context.Questions.Add(new Questions { Description = "You must consider all the factors in the decision and determine which is the least restrictive physically, psychologically and socially for the person.  If a more restrictive option is chosen and it amounts to a deprivation of liberty(depending on the circumstances) you may need to consider a Deprivation of Liberty Safeguards(DoLS) application", id = "36", yes_button = "5", yes_next = "42", no_next = "37" });
            context.Questions.Add(new Questions { Description = "Proceed to making the decision and document how the decision was made on the relevant forms.", id = "37" });
            context.Questions.Add(new Questions { Description = "An Independent Mental Capacity Advocate (IMCA) must be instructed when the person is found to lack capacity and a best interest decision is needed and the person has no appropriate person (friends or family) to consult on the following decisions:<br/>\u2022  Serious medical treatment <br/>\u2022  A change of accommodation ", id = "38", yes_button = "3", yes_next = "39" });
            context.Questions.Add(new Questions { Description = "In addition, there is a duty in the NHS and social care settings to consider requesting an IMCA in the following circumstances: <br/>\u2022 Safeguarding Adults from Abuse<br/>\u2022 Care Reviews  ", id = "39", yes_button = "3", yes_next = "40" });
            context.Questions.Add(new Questions { Description = "The IMCA’s role in these circumstances is to:<br/>\u2022Gather the views and beliefs of person <br/>\u2022 Evaluate all the relevant information <br/>\u2022 Provide a written report to assist the decision maker (e.g.Doctor) ", id = "40", yes_button = "3", yes_next = "41" });
            context.Questions.Add(new Questions { Description = "If you need to instruct an IMCA please contact the Hertfordshire service (POhWER) via:<br/> Email: <a href='mailto: pohwer@pohwer.net'>pohwer@pohwer.net</a><br>Website:<a href='http://www.pohwer.net/index-13.html'>POhWER</a><br>Telephone:<a href= 'tel:0300 456 2370'>0300 456 2370</a> ", id = "41" });
            context.Questions.Add(new Questions { Description = "The Supreme Court has found that the test to determine if the person is being deprived of their liberty depends on 3 criteria:<br/>\u2022 The person lacks mental capacity to decide to remain in the care setting <br/>\u2022 The person is under continuous supervision and control <b>and</b> <br/>\u2022 The person is not free to leave the care setting. ", id = "42", yes_button = "3", yes_next = "43" });
            context.Questions.Add(new Questions { Description = "Can the person consent to remain in the care setting following a mental capacity assessment?", id = "43", yes_button = "1", no_button = "1", yes_next = "46", no_next = "44" });
            context.Questions.Add(new Questions { Description = "Have you completed your organisations MCA & BID forms for this decision?", id = "44", yes_button = "1", yes_next = "45" });
            context.Questions.Add(new Questions { Description = "Is the person 18yrs or older?", id = "45", yes_button = "1", no_button = "1", yes_next = "47", no_next = "46" });
            context.Questions.Add(new Questions { Description = "The person does not meet the DoLS assessment criteria.<br/> Please review the persons care plan and allow them to leave. Document the unwise decision, consider applying the Mental Health Act or seek legal advice.", id = "46" });
            context.Questions.Add(new Questions { Description = "Does the person have a mental disorder? (such as dementia, learning disability, confusion, concussion, etc?) ", id = "47", yes_button = "1", no_button = "1", yes_next = "57", no_next = "48" });
            context.Questions.Add(new Questions { Description = "The person does not meet the DoLS assessment criteria.<br/> Please review the persons care plan and allow them to leave. Document the unwise decision, consider applying the Mental Health Act or seek legal advice.", id = "48" });
            context.Questions.Add(new Questions { Description = "Is there no less restrictive way to provide the care the person needs?", id = "57", yes_button = "1", no_button = "1", yes_next = "51", no_next = "52" });
            context.Questions.Add(new Questions { Description = "The person appears to have capacity to give valid consent for this decision. Please document this assessment in the persons record", id = "50" });
            context.Questions.Add(new Questions { Description = "Please review the persons care arrangements to minimise restriction and record rationale in the persons care records.", id = "51" });
            context.Questions.Add(new Questions { Description = "Does the person meet the criteria for detention under the Mental Health Act.", id = "52", yes_button = "1", no_button = "1", yes_next = "54", no_next = "56" });
            context.Questions.Add(new Questions { Description = "A person is not eligible for the Deprivation of Liberty Safeguards if they are eligible for assessment under the Mental Health Act.", id = "54" });
            context.Questions.Add(new Questions { Description = "The person appears to have capacity to give valid consent for this decision. Please document this assessment in the persons record.", id = "55" });
            context.Questions.Add(new Questions { Description = "The person meets the criteria for a DoLS application, this application can be completed in 2 parts on the same combined form:<br/> Urgent Authorisation(self authorise for max. 7 days)<br/> Standard Application <br/> When making your application to the DOLS team, please ensure that all relevant information relating to any Lasting Power of Attorney, Advance Decision or Court of Protection order is included in the application. Contact and send the application form to the DoLS team dolsteam@hertfordshire.gov.uk as per your local process.", id = "56" });



            base.Seed(context);
        }
    }
}